### ISSUE TITLE
How do I install a local module?

### ISSUE THREAD

**Issue by kgoedert** [bitnami/bitnami-docker-magento#137]
I created a simple module with an observer following this tutorial https://www.cloudways.com/blog/create-module-in-magento-2/

But after running setup:upgrade my module is listed, but a lot of errors occur in magento, for example the admin module does not work anymore.

How can I fix this?

**Comment by carrodher** [comment]
In order to try to reproduce the issue in our side, please can you provide the following information:

- Where are you placing the module? Any output of the `ls -la` command will be helpful.
- What are the exact errors after running `setup:upgrade`? Can you paste also the commands you're running before the issue?

**Comment by britztopher** [comment]
I tried to install a simple HelloWorld module from this tutorial 
https://www.mageplaza.com/magento-2-module-development/view-block-layout-template-magento-2.html
