### ISSUE TITLE
adding bitnami/rabbitmq to the bitnami/magento

### ISSUE THREAD

**Issue by androdebugur** [bitnami/bitnami-docker-magento#146]
Hi, I am using bitnami/magento docker, everything works well, thank you for this. I need to add rabbitmq to it, i can do it by adding bitnami/rabbitmq to the bitnami/magento docker-compose.yml file. But how do I configure username password ports etc so that magento can use and access the rabbitmq. Please help me set these two up with the default values.

Thank you very much.

**Comment by marcosbc** [comment]
Hi @androdebugur, is there any reason for using RabbitMQ for message queues, instead of MySQL/MariaDB (default configuration)?

To enable RabbitMQ in Magento follow the steps below:

> Note that all this is documented in their official documentation: https://devdocs.magento.com/guides/v2.3/install-gde/prereq/install-rabbitmq.html#connect-rabbitmq-to-magento-open-source-or-magento-commerce

Edit the `/opt/bitnami/magento/htdocs` file

```diff
@@ -4,7 +4,14 @@
         'frontName' => 'admin'
     ],
     'queue' => [
-        'consumers_wait_for_messages' => 1
+        'consumers_wait_for_messages' => 1,
+        'aqmp' => [
+            'host' => 'rabbitmq',
+            'port' => '25672',
+            'user' => 'user',
+            'password' => 'bitnami',
+            'virtualhost' => '/'
+        ]
     ],
     'crypt' => [
         'key' => 'ca25823b0f2c7ac590f170d7f44c625a'
```

Add RabbitMQ to the Docker Compose:

```diff
@@ -31,7 +31,13 @@
     image: 'docker.io/bitnami/elasticsearch:6-debian-10'
     volumes:
       - 'elasticsearch_data:/bitnami/elasticsearch/data'
+  rabbitmq:
+    image: 'docker.io/bitnami/rabbitmq:3.8-debian-10'
+    volumes:
+      - 'rabbitmq_data:/bitnami'
 volumes:
+  rabbitmq_data:
+    driver: local
   elasticsearch_data:
     driver: local
   mariadb_data:
```

Restart services:

```console
$ docker-compose down
$ docker-compose up -d
$ docker-compose logs -f
```

If you find any issues, we recommend you check [Magento support forums](https://community.magento.com/) as they will be able to provide specific help for the Magento application.
