### ISSUE TITLE
do action after magento installed in dockerfile

### ISSUE THREAD

**Issue by mehrdadhosseinzadeh** [bitnami/bitnami-docker-magento#173]
hi to all
i want  to clone module and theme and copy theme into app/code and app/design/frontend

after that i want to run 

php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento setup:static-content:deploy -f
php bin/magento indexer:reindex
php bin/magento cache:flush

but get error because my magento not install yet...

i want to do action after complete installed my magento and after that i want to run bin/magneto .... and composer require ...

another question :

my custom themes copy into app/design/frontend/vendor/theme

how i can to set as default theme as cli ?

**Comment by andresbono** [comment]
I'm not really sure if that is possible. Note that the installation of Magento happens when you run the container so if you are running the commands in the Dockerfile, that might be the cause of the error about "magento not installed yet".

Here you can find a previous issue mentioning the topics of modules and themes:

https://github.com/bitnami/bitnami-docker-magento/issues/107

Also please note that we are currently working on a big new release of the configuration logic for Magento that will be available soon. It is possible that you need to adapt any changes you do to the new configuration format.

**Comment by mehrdadhosseinzadeh** [comment]
@andresbono 
thank you for answer my question and problem.

i read dockefile structure and found it 

bitnmai magento docker image  has step init and postInit

- ./Docker/app/postInit:/docker-entrypoint-init.d

i mount a local folder to /docker-entrypoint-init.d folder

this folder must create and exist on root folder
if this folder exist 
bitnami docker post init run all .sh files in this folder
you can put your script(s) to this folder for run after installed or initialized of magento

**Comment by andresbono** [comment]
@mehrdadhosseinzadeh, do you mean that you are executing the commands from your first comment by using a script that is executed during the post init stage?

What is the error that you get? Still the "magento not install yet"? Please share with us any logs you may have. It would also be helpful if you share the script that you are mounting in `/docker-entrypoint-init.d` and the docker-compose that you are using.

**Comment by marcosbc** [comment]
Hi @mehrdadhosseinzadeh, we have just released a new major release of the Bitnami Docker image for Magento, [2.4.1-debian-10-r80](https://github.com/bitnami/bitnami-docker-magento#241-debian-10-r80). It includes major changes with respect to how the image is initialized, and now the source code for the initialization scripts is also published in the [rootfs](https://github.com/bitnami/bitnami-docker-magento/tree/master/2/debian-10/rootfs) folder of this repo.

Since the source code is now open-sourced in the repo, if you are using 2.4.x you could always extend the Docker container and modify the initialization scripts to add any extra commands in [setup.sh](https://github.com/bitnami/bitnami-docker-magento/blob/master/2/debian-10/rootfs/opt/bitnami/scripts/magento/setup.sh) or [libmagento.sh](https://github.com/bitnami/bitnami-docker-magento/blob/master/2/debian-10/rootfs/opt/bitnami/scripts/libmagento.sh#L135).
