### ISSUE TITLE
Feature request: Option to disable Magento configuration/installation

### ISSUE THREAD

**Issue by mysil2** [bitnami/bitnami-docker-magento#177]
It would've been great to have an option to disable configuration/installation of Magento. When running a multi-server environment pointing to the same database, running the installation if persistence for some reason is missing (network drive error, user error etc.) messes up the existing database/installation.

**Comment by andresbono** [comment]
Hi @mysil2, could you check if `MAGENTO_SKIP_BOOTSTRAP` is what you are looking for?

**Comment by mysil2** [comment]
Not really. As far as I can see, that's only a small step: https://github.com/bitnami/bitnami-docker-magento/blob/77698d10219406b19112754cd2d5a66169b22bde/2/debian-10/rootfs/opt/bitnami/scripts/libmagento.sh#L222

I think this is where the check I'm looking for really is: https://github.com/bitnami/bitnami-docker-magento/blob/77698d10219406b19112754cd2d5a66169b22bde/2/debian-10/rootfs/opt/bitnami/scripts/libmagento.sh#L140

Which is checking if there is something persisted: https://github.com/bitnami/bitnami-docker-magento/blob/77698d10219406b19112754cd2d5a66169b22bde/2/debian-10/prebuildfs/opt/bitnami/scripts/libpersistence.sh#L114

**Comment by ganeddact** [comment]
I'm supporting mysil2 request.
Even if I want to start from scratch a new installation, I can't mount any module in app/code or theme in app/design, as mounting will create /bitnami/magento/app/code/Vendor/ModuleName and so /bitnami/magento won't be empty and that check
`if ! is_app_initialized "$app_name"; then `
will fail, causing the container to fail as magento is not installed and the database is empty.
You should probably check if folders created after magento installation are created (i.e. bin), not the main folder

**Comment by marcosbc** [comment]
Hi @mysil2, have you considered mounting the entire Magento directory onto `/bitnami/magento`? That would allow you to skip configuration (it will be considered as already initialized and only the DB schema will be upgraded).

Alternatively, you could always just override the entire container entrypoint/cmd if you want to skip the entire initialization altogether.

@ganeddact Unfortunately we're unable to support mounting specific files onto "app/code" or other locations, as there is no clear data-code separation in Magento, requiring the entire Magento folder to be persisted. Instead, you would have to follow one of these steps:

* Install module/theme/other at Docker `build` time (by [extending the Docker image](https://github.com/bitnami/bitnami-docker-magento#extend-this-image)).
* Deploy a new Magento install and install your new module/theme/other manually. Since the entire Magento directory is persisted, no data will be lost after re-deploying with existing volumes.
* Deploy a new Magento and install module/theme/other via init scripts (mounting to [`/docker-entrypoint-init.d`](https://github.com/bitnami/bitnami-docker-magento/blob/master/2/debian-10/rootfs/post-init.sh#L11)). Same as the above step, but automating the customization part.
* Mount a pre-installed Magento with the module/theme/other already installed (like I mentioned in my first paragraph).

**Comment by mysil2** [comment]
> Hi @mysil2, have you considered mounting the entire Magento directory onto `/bitnami/magento`? That would allow you to skip configuration (it will be considered as already initialized and only the DB schema will be upgraded).

Thanks for the suggestion - I guess that would do it!

**Comment by ganeddact** [comment]
> @ganeddact Unfortunately we're unable to support mounting specific files onto "app/code" or other locations, as there is no clear data-code separation in Magento, requiring the entire Magento folder to be persisted. Instead, you would have to follow one of these steps:
> 
> * Install module/theme/other at Docker `build` time (by [extending the Docker image](https://github.com/bitnami/bitnami-docker-magento#extend-this-image)).
> * Deploy a new Magento install and install your new module/theme/other manually. Since the entire Magento directory is persisted, no data will be lost after re-deploying with existing volumes.
> * Deploy a new Magento and install module/theme/other via init scripts (mounting to [`/docker-entrypoint-init.d`](https://github.com/bitnami/bitnami-docker-magento/blob/master/2/debian-10/rootfs/post-init.sh#L11)). Same as the above step, but automating the customization part.
> * Mount a pre-installed Magento with the module/theme/other already installed (like I mentioned in my first paragraph).

Thanks for the suggestion, it's useful indeed
