### ISSUE TITLE
App initialization check is prone to failure.

### ISSUE THREAD

**Issue by jeff-french** [bitnami/bitnami-docker-magento#184]
The installation of Magento can take a very long time and the container may get shutdown before it has written all files to the final `/bitnami/magento` folder when persisting the installation. This results in the initialization scripts thinking that the entire installation as already been persisted and installation should be skipped on subsequent starts of the container. I think a better solution would be to write a specific file _after_ successfully persisting the installation and then check for the existence of that file for the `is_app_initialized` call. 

https://github.com/bitnami/bitnami-docker-magento/blob/04359d3643b395491f723bf03ceb2ca1db3d22ec/2/debian-10/rootfs/opt/bitnami/scripts/libmagento.sh#L140

**Comment by marcosbc** [comment]
Hi @jeff-french, we have discussed that approach internally before but in the end did not go for it, because a failed initialization will still leave data in the volume, leaving the original initialization not know how to proceed.

Note that we want to avoid at all costs removing a volume for failed initializations, as it could be very problematic.

Instead, we recommend either to re-deploy with increased liveness/readiness probes until it succeeds, or to deploy in a "diagnostic"-like mode. In Bitnami charts you can do that with `--set 'command[0]=sleep,command[1]=infinity'` and disabling liveness/readiness probes.

**Comment by jeff-french** [comment]
I don't think you'd have to _remove_ the volume. If the "initialization complete" file doesn't exist the container would just start the initialization process again on top of the existing files. 

Anyway, I'll go ahead and close this. This is not an issue for me anymore as I built my own container since this one has way too many moving parts and is prone to failure.

**Comment by marcosbc** [comment]
I'm sorry to hear that, but thanks for the honest feedback. I'm going to create an internal task for reviewing this particular issue and to discuss ways to improve it.

> I don't think you'd have to remove the volume. If the "initialization complete" file doesn't exist the container would just start the initialization process again on top of the existing files.

In that particular case, we're worried that it may cause unexpected issues for whenever there has been a data loss, causing files to be lost/overwritten because of it. Maybe the best thing we can do is just to abort the initialization entirely if the volume is not empty but the "initialization complete" file exists, with a useful warning message.
