### ISSUE TITLE
Bringing back up a persisted Magento installation set on prod mode

### ISSUE THREAD

**Issue by ganeddact** [bitnami/bitnami-docker-magento#193]
**Description**

If a server issue cause the Magento container to stop, when bringing up the Magento site with docker compose up the script in /opt/bitnami/scripts/libmagento.sh will see the persisted installation and won't install Magento, correctly, but will run setup:upgrade (line 344).
At the end of the command, after Apache is declared started, trying to open the homepage will end in a blank page with a var/report file number, that contains "Unable to retrieve deployment version of static files from the file system".
If the site is in production mode, that setup:upgrade probably triggers the generated code to be lost and the need to redeploy again? If so, how is it possible to run the setup:di:compile and setup:static-content:deploy commands after that?
I think I'm missing something obvious as this would affect many people not just me.

**Steps to reproduce the issue:**

1. Have a Bitnami Magento installation set on production mode
2. Stop it or bring it down
3. Bring it back up

**Describe the results you received:**

Docker composition is brought up, but the site will display:
_There has been an error processing your request
Exception printing is disabled by default for security reasons.
Error log record number XXXXXXX_

Going to var/report, the report contains "Unable to retrieve deployment version of static files from the file system"

**Describe the results you expected:**

Site being brought up without need to recompile

**Comment by alemorcuq** [comment]
Hi, @ganeddact.

I've been able to reproduce the issue. The static files should be persisted as well, but apparently they are not. We are currently investigating the issue.

**Comment by lukasz-zimnoch** [comment]
+1 here. As @ganeddact mentioned, looks like this happens because of `setup:upgrade` being executed in the case when Magento directory is present. During the upgrade, generated code and static content are pruned. As a workaround, one can perform `setup:di:compile` and `setup:static-content:deploy` within an init script but this takes a lot of time and makes usage of pre-compiled packages worthless. Maybe it would be good to introduce a flag (e.g. via env variable) that will allow disabling the `setup:upgrade` step if necessary?

**Comment by alemorcuq** [comment]
I will add that suggestion to the task. Thanks, @lukasz-zimnoch.

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-magento#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
