### ISSUE TITLE
Build custom theme into image

### ISSUE THREAD

**Issue by mahgo** [bitnami/bitnami-docker-magento#195]
**Description**

I'm wanting to make my own image based on this one, and I'm wanting to build in my own custom theme. How can I achieve this?

**Comment by juan131** [comment]
Hi @mahgo 

Please refer to the instructions below to get information about how to extend this image:

- https://github.com/bitnami/bitnami-docker-magento#customize-this-image

**Comment by mahgo** [comment]
Hi @juan131,

I can't see anything that that points me in the direction of custom themes.

Is there any documentation on how to add extra files into the /bitnami/magento folder at least? That might give me something to work with, if there isn't explicit custom theme support with this image.

**Comment by juan131** [comment]
Hi @mahgo 

I am afraid we don't have such documentation. 

Magento files are, by default, under the `/opt/bitnami/magento` directory. However, when the container is initialized for the 1st time (the 1st time you run the container) they're moved to `/bitnami/magento` and symlinks are created pointing from `/opt/bitnami/magento` to `/bitnami/magento`. This is done since we recommend mounting volumes at `/bitnami/magento` to persist the application, this way whatever modification you do to Magento while running the app will survive to container restarts.

To mount your custom files while extending the image (build time), you should mount them under the `/opt/bitnami/magento`. For instance, copying them at `/opt/bitnami/magento/app/design/frontend/` (see https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/themes/theme-structure.html). Once you run the container, your custom files (along with the rest of the Magento files) will be moved to `/bitnami/magento` as I explained before.

---

All the scripts that are used to automate the installation and deployment of Magento (along with PHP and Apache) are open-source and can be found in the directory below:

- https://github.com/bitnami/bitnami-docker-magento/tree/master/2/debian-10/rootfs/opt/bitnami/scripts

Consult them to learn more about the automations we do.

**Comment by mahgo** [comment]
Hi @juan131 

Thanks for that. In my dockerfile, I'm calling `ADD` on the folders that need to be added and am adding them where they need to be. I'm also calling `RUN chmod g+rwX` on these folders, as that seems to be needed as well. Without this, the container failed to start. Is this correct? 

I'm having a strange issue where going to /admin for the first time is causing a container (the magento container or an elasticsearch container) to be evicted and recreated. This is not an issue that occurs when I'm not adding my custom theme into my custom image. Do you know why this might be?

**Comment by juan131** [comment]
Hi @mahgo 

>  I'm also calling RUN chmod g+rwX on these folders, as that seems to be needed as well. Without this, the container failed to start. Is this correct?

The "daemon" user should have read permissions on these folder, unless writing permissions are required. You can use the line below as inspiration:

- https://github.com/bitnami/bitnami-docker-magento/blob/master/2/debian-10/rootfs/opt/bitnami/scripts/libmagento.sh#L211

> I'm having a strange issue where going to /admin for the first time is causing a container (the magento container or an elasticsearch container) to be evicted and recreated. This is not an issue that occurs when I'm not adding my custom theme into my custom image. Do you know why this might be?

That's hard to tell without more information:

- Does the rest of functionalities work as expected?
- Did you find anything weird in the Apache logs (they're redirected to stdout/stderr by default)?

**Comment by mahgo** [comment]
Hi @juan131,

Thanks for confirming that. Am I correct in understanding that that line makes folders 775 and files 664? What would be the easiest way to achieve this in a Dockerfile?

In regards to the eviction issue, I've actually had it now happen when not adding this custom theme to the image, so I won't worry about this for now. When it happens again, I'll check the Apache logs, thanks.

**Comment by juan131** [comment]
Hi @mahgo 

> Thanks for confirming that. Am I correct in understanding that that line makes folders 775 and files 664?

Yes, please also ensure the files/directories belong to the "daemon" user

> What would be the easiest way to achieve this in a Dockerfile?

You can simply use a "RUN" layer in your Dockerfile and execute the required chown/chmod commands. Find more info in the [Dockerfile reference](https://docs.docker.com/engine/reference/builder/).

**Comment by mahgo** [comment]
Thanks for your help @juan131
