### ISSUE TITLE
[Feature request] Adding environment variable for PHP timezone

### ISSUE THREAD

**Issue by camo-f** [bitnami/bitnami-docker-magento#215]
Hello,

It seems to be hard to configure the PHP timezone for this container. I tried to use `TZ` environment variable, but PHP ignores it.
Another option would be using `post-init.d` scripts, however `post-init` is only executed once, so it requires persisting PHP configuration files.
 
There is already a mechanism to update some PHP configuration options, for instance `PHP_MAX_EXECUTION_TIME`.
Adding an environment variable `PHP_DATE_TIMEZONE` would allow to configure PHP timezone really easily using this mechanism.

Does it look doable for you ?

Thanks in advance !

**Comment by pablogalegoc** [comment]
Hi @camo-f!

As you point out, there are some instances of environment variables for PHP configurations. I'd recommend looking for `PHP_EXPOSE_PHP` (instead of `PHP_MAX_EXECUTION_TIME`) because it doesn't set a default value. Since the timezone parameter is also controlled by a ini file option (`date.timezone`) you can easily add a `PHP_DATE_TIMEZONE` using `PHP_EXPOSE_PHP` as example. Feel free to open a PR if you think this is a good addition to the container, we'll be happy to review it!

**Comment by pablogalegoc** [comment]
Thanks for your contribution @camo-f!
