### ISSUE TITLE
Chown on /bitnami/magento is forbidden on EFS usug Accerss points

### ISSUE THREAD

**Issue by allamand** [bitnami/bitnami-docker-magento#223]
**Description**

When plugin magento directory /bitnami/magento into an EFS external volume for persistency, it won't work because the setup scripts try to do a chown on this directory which is forbidden by the access points mode of EFS (`chown: changing ownership of ‘/bitnami/magento/’: Operation not permitted`)

Is there a way to disable the chown of the directory by the setup script ?

**Comment by marcosbc** [comment]
Hi @allamand, currently it is executed when running the Magento container image as `root`, as you can see [here](https://github.com/bitnami/bitnami-docker-magento/blob/master/2/debian-10/rootfs/opt/bitnami/scripts/libmagento.sh#L219).

The reason for this action is so that users don't need to worry about configuring permissions when running as `root`. You can try and run Magento as a non-root user for now to avoid it. If you have any suggestions or ideas on how to improve the logic, feel free to contribute with a PR, we'd be happy to consider it!

**Comment by marcosbc** [comment]
That said, it seems like this issue is specific to when `root squashing` is enabled (https://serverfault.com/questions/212178/chown-on-a-mounted-nfs-partition-gives-operation-not-permitted). I'd say that this feature is not supported for Bitnami containers when running as a root user.

**Comment by allamand** [comment]
Thanks, I'll try with running as non root.

**Comment by juan131** [comment]
Great! Please let us know if you find any issue running the container as non-root.
