### ISSUE TITLE
Upgrading to Magento 2.4.4

### ISSUE THREAD

**Issue by hussam-qasem** [bitnami/bitnami-docker-magento#245]
### Name and Version

bitnami/magento:2.4.3

### What is the problem this feature will solve?

Adobe just announced [Magento Open Source 2.4.4](https://devdocs.magento.com/guides/v2.4/release-notes/open-source-2-4-4.html).

What is the process by which Bitnami will provide an upgraded 2.4.4 Docker image?

### What is the feature you are proposing to solve the problem?

Upgrade to [Magento Open Source 2.4.4](https://devdocs.magento.com/guides/v2.4/release-notes/open-source-2-4-4.html).

### What alternatives have you considered?

N/A.

Side question: does Magento Open Source or Bitnami provide an upgrade path to security-only patches? E.g. **2.4.3-p2**?

**Comment by carrodher** [comment]
Thanks for letting us know. Our test & release pipeline already detected the new version but it requires manual intervention on our side due to some of the changes introduced in that version.

We will update this thread once released the new version.

> Side question: does Magento Open Source or Bitnami provide an upgrade path to security-only patches? E.g. 2.4.3-p2?

At this moment, Bitnami only provides updates for new major, minor or patch versions.

**Comment by harli91** [comment]
any news on this?

**Comment by carrodher** [comment]
Still in progress, due to the team capacity, other priorities and the number of supported applications in the catalog, this kind of major (non-automated) change can take more than expected; but we are working on it and we will update this issue once released.

**Comment by ganeddact** [comment]
As probably others have noticed, you released the 2.4.4 image.
May I ask why has been decided to implement PHP 8.1 straight away?
Many third-party module developers are not ready for that PHP version, and I suppose many won't adopt that image for a while because many modules won't work.
I don't know how much is feasible, but a parameter in the docker-compose.yml file to decide which PHP version to use 7.4/8.1 would have been spot on.

**Comment by carrodher** [comment]
We are following the version recommended by the Magento developers, see https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html

If there is any kind of issue regarding the PHP version, I think the best option is to create an issue in the Magento GH repo or any other support forum monitoring by them

**Comment by ganeddact** [comment]
Of course we all should aim to the target aimed by the Magento core team, but in the real world Magento is usually never used out of the box without any third-party module. The possibility to choose the PHP version, at this stage when the jump is being imposed maybe too soon, would have been really appreciated.
I'll have to stick to the 2.4.3 tag and upgrade from inside the container until all our third-party modules (or the ones we can afford to replace/drop) are ready.
