### ISSUE TITLE
Only homepage works for me

### ISSUE THREAD

**Issue by bhanuc** [bitnami/bitnami-docker-magento#43]
I was trying to do a local installation on ubuntu but only first link is reachable which is ``` http://127.0.0.1/index.php/?SID=p3og3poo5g5khsn7g9a37itv75 ```
and subsequent links like ```https://127.0.0.1/index.php/customer/account/login/ ``` are not reachable. It is mostly due to https nature of the followup links. Any help/resolution would be really beneficial.

**Comment by sameersbn** [comment]
The image is pre-configured  with self signed SSL certificates and https support is expected to work out of the box. Since the certificates are self signed your browser will prompt you to manually accept the authenticity of these certificates before continuing. Are you not able to load the https links? what is the error message you are seeing.

**Comment by prydonius** [comment]
You will need to ensure that port 443 is being forwarded as well as port 80 to the host.
